version: "3.9"

services:
  app:
    image: app
    container_name: app
    restart: always
    user: user
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/home/user/app
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 1m"
      ofelia.job-exec.app.command: "websiteChecker"

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro